=== amylmiller7/XML/OngoingEducation/OngoingEducationJava/OngoingEducation1.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!-- Enforces rules concerning data in XML file. -->
<!-- standard design schema -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" >
	
<xs:element name="list">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="item" maxOccurs="unbounded" >
				<xs:complexType>
					<xs:sequence>
						
						<!-- title: string, cannot be empty -->
						<xs:element name="title">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:minLength value="1" />
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						
						<!-- subject: string, cannot be empty, comma delimited list, items 1+ word initial upper case followed by upper or lower case -->
						<xs:element name="subject" >
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="jQuery|[A-Z][a-zA-Z]+[ ]*[a-z]*(,\s[jQuery]|,\s[A-Z][a-zA-Z]+[ ]*[a-z]*)*" />
								</xs:restriction>			
							</xs:simpleType>
						</xs:element>
						
						<!-- institution: string, cannot be empty -->
						<xs:element name="institution">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:minLength value="1" />
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						
						<!-- type: string, cannot be empty, choice -->
						<xs:element name="type">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="Online course|Online tutorial|Online workshop|In-person course|In-person workshop|Online certificate course|In-person certificate course" />
								</xs:restriction>		
							</xs:simpleType>
						</xs:element>
						
						<!-- location: string; initial upper case; word+ @ {city}, {state}; or {city}, {state}; or em-dash; cannot be empty -->
						<xs:element name="location">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="â€”|https?://.+|[A-Z][a-zA-Z]+([ ][a-zA-Z]+[ ]\@[ ])[A-Z][a-zA-Z]+([ ][A-Z][a-zA-Z]+)*(,\s)[A-Z][a-zA-Z]|[A-Z][a-zA-Z]+([ ][A-Z][a-zA-Z]+)*(,\s)[A-Z][a-zA-Z]"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						
						<!-- instructor: string, cannot be empty -->
						<xs:element name="instructor">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:minLength value="1" />
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
					
						<!-- date: string; month year; month year+; month-month year; month day, year; month day-day, year; month year-month year -->
						<xs:element name="date" >
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="In progress|([A-Z][a-z]+[-])*([A-Z][a-z]+[ ]20[0-1][0-9][-])*[A-Z][a-z]+([ ]\d{1,2}[,])*([ ]\d{1,2}[-]\d{1,2}[,])*([ ]20[0-1][0-9]+)[+]*" />
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						
						<!-- sortDate: string, yyyy-mm OR yyyy-mm-dd -->
						<xs:element name="sortDate">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="20[0-1][0-9\-]+[0-3][0-9\-]+([0-1][0-9])*" />
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						
						<!-- javaScriptDate: string, mm/yyyy, m/yyyy, mm/dd/yyyy, m/dd/yyyy, m/d/yyyy
						<xs:element name="javaScriptDate">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="In progress|([0-1]*[0-9]\/)+([0-3]*[0-9]\/)*(20[0-1][0-9])+"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
                      -->
						
						<!-- description: string, start with upper case, can end with period -->
						<xs:element name="description">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="[A-Z].+[\.]*"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						
						<!-- category: at least one but not more than 5, choice -->
						<xs:element name="category" maxOccurs="7">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="OAuth|Testing|AWS|HTTP|AI|Machine learning|SDK|docs as code|JavaScript|Scripting|jQuery|Programming|Object-Oriented|PHP|Ruby|Web services|API|REST|SOAP|JSON|Git|GitHub|Command line|Web development|Web design|HTML|XML|CSS|XHTML|CMS|SharePoint|InDesign|Publishing|Technical editing|Content management|Minimalism|DITA|Technical communication|Technical writing|RoboHelp|Visio|Images|Photoshop|WordPress|Swagger|OAS|YAML|Jenkins|Maven|DevOps|Java"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>
	
</xs:schema>

=== amylmiller7/XML/OngoingEducation/OngoingEducationJava/OngoingEducation.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="OngoingEducation.xsl"?>
<!-- Lists recent coursework (online/in-person) on technical communication, programming, web design, and other topics. -->
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="OngoingEducation1.xsd">
      <item>
        <title>AWS Essentials 2019</title>
        <subject>AWS</subject>
        <institution>Udemy/Linux Academy</institution>
        <type>Online course</type>
        <location>—</location>
        <instructor>Tia Williams</instructor>
        <date>October 31, 2019</date>
        <sortDate>2019-10-31</sortDate>
        <description>Linux Academy's AWS Essentials course is designed for those who want to learn the core services, features, and benefits of AWS, while also gaining valuable hands-on experience.  This course covers all the basics, including creating an AWS account, configuring access management; virtual networking, routing, and security; compute, storage, and database services; monitoring and metrics; fundamental cloud/AWS terminology.</description>
        <category>AWS</category>
      </item>
       <item>
        <title>AWS Concepts</title>
        <subject>AWS</subject>
        <institution>Udemy/Linux Academy</institution>
        <type>Online course</type>
        <location>—</location>
        <instructor>Thomas Haslett</instructor>
        <date>September 19, 2019</date>
        <sortDate>2019-09-19</sortDate>
        <description>This course is to provide a simple, conceptual introduction to the concepts of Cloud Computing and Amazon Web Services.</description>
        <category>AWS</category>
      </item>
       <item>
        <title>Web Security: OAuth and OpenID Connect</title>
        <subject>OAuth</subject>
        <institution>Lynda.com</institution>
        <type>Online course</type>
        <location>—</location>
        <instructor>Keith Casey</instructor>
        <date>September 25, 2019</date>
        <sortDate>2019-09-25</sortDate>
        <description>While many technical professionals claim to know and understand OAuth, reality often suggests otherwise. Implementing the proper grant types and the required flows while securely protecting your secrets is challenging at best and catastrophic at worst. Fundamentally, professionals often struggle with OAuth because they misunderstand what it is, what use cases it is particularly good and bad at, and how to integrate it smoothly and safely into their systems. In this course, review the basics of OAuth 2.0 and OpenID Connect, and learn how to use them to authenticate your applications. Learn about tokens, scopes, and claims; OAuth flows; common security considerations; and more.</description>
        <category>OAuth</category>
      </item>
       <item>
        <title>API Testing and Validation</title>
        <subject>API</subject>
        <institution>Lynda.com</institution>
        <type>Online course</type>
        <location>—</location>
        <instructor>Keith Casey</instructor>
        <date>September 16, 2019</date>
        <sortDate>2019-09-16</sortDate>
        <description>Most API testing doesn't actually test the API. This course shows how to validate your API from the consumer's point of view, testing to confirm that problems experienced by your end users are being solved. Join Keith Casey as he focuses on how to approach API testing by implementing a behavior-driven development model. Keith uses Gherkin to set up a Behat environment so you can see how to write and run your first test. Then, he shows how to build API test requests, including how to introduce variables, authenticate requests, and validate responses. He also covers refactoring tests, establishing system states, using extensions for batch operations, and more.</description>
        <category>API</category>
        <category>Testing</category>
      </item>
       <item>
        <title>Designing RESTful APIs</title>
        <subject>API</subject>
        <institution>Lynda.com</institution>
        <type>Online course</type>
        <location>—</location>
        <instructor>Keith Casey</instructor>
        <date>August 30, 2019</date>
        <sortDate>2019-08-30</sortDate>
        <description>Having a solid understanding of how to correctly build APIs is important for any developer planning on creating websites. In this course, learn how to plan and model your own APIs, and explore the six REST design constraints that help guide your architecture. Keith Casey starts with a simple overview, including advice on identifying the users or "participants" of your system, and the activities they might perform with it. He discusses how to validate your design before you build it, and explores the HTTP concepts and REST constraints needed to build your API. To wrap up, Keith goes over some of the most common API design patterns you may encounter.</description>
        <category>API</category>
      </item>
       <item>
        <title>HTTP Essential Training</title>
        <subject>HTTP</subject>
        <institution>Lynda.com</institution>
        <type>Online course</type>
        <location>—</location>
        <instructor>Morten Rand-Hendriksen</instructor>
        <date>August 30, 2019</date>
        <sortDate>2019-08-30</sortDate>
        <description>Hypertext Transfer Protocol (HTTP) is one of the most utilized protocols on the internet. In this course, instructor Morten Rand-Hendriksen helps you bolster your understanding of how HTTP works by reviewing fundamental concepts. He begins by explaining what HTTP is, and then covers key terminology and the HTTP flow. He then discusses the request/response pair, HTTP methods, and status messages. To wrap up, he goes over HTTP headers, explaining what they are and how to see them.</description>
        <category>HTTP</category>
      </item>
       <item>
        <title>Learning REST APIs</title>
        <subject>API</subject>
        <institution>Lynda.com</institution>
        <type>Online course</type>
        <location>—</location>
        <instructor>Morten Rand-Hendriksen</instructor>
        <date>August 23, 2019</date>
        <sortDate>2019-08-23</sortDate>
        <description>Learn the basics of REST APIs. In this course, discover what REST APIs are, why they matter, and how putting them to use can help you build faster, more efficient applications. Review how HTTP and REST APIs relate, explore the six constraints of REST, and learn about HTTP status messages. Learn how to get started with consuming REST APIs to incorporate them into data-driven applications.</description>
        <category>API</category>
        <category>REST</category>
      </item>
      <item>
        <title>AI For Everyone</title>
        <subject>AI</subject>
        <institution>Coursera</institution>
        <type>Online course</type>
        <location>—</location>
        <instructor>Andrew Ng</instructor>
        <date>March 25, 2019</date>
        <sortDate>2019-03-25</sortDate>
        <description>Introduction to AI: defined AI, discussed machine learning, what makes valuable data, limitations of machine learning, deep learning and neural networks, what an AI project looks like.</description>
        <category>AI</category>
        <category>Machine learning</category>
    </item>
    <item>
        <title>Crash course in API documentation</title>
        <subject>API</subject>
        <institution>STC summit 2019</institution>
        <type>Online workshop</type>
        <location>https://idratherbewriting.com/blog/crash-course-in-api-documentation/</location>
        <instructor>Tom Johnson</instructor>
        <date>May 25, 2010</date>
        <sortDate>2019-05-25</sortDate>
        <description>Compressed introduction to APIs: what are they, components of API documentation, OpenAPI specification, static site generators, reference vs. conceptual documentation, docs as code.</description>
        <category>API</category>
        <category>SDK</category>
        <category>docs as code</category>
    </item>
    <item>
        <title>Java 8 Essential Training</title>
        <subject>Java</subject>
        <institution>Lynda.com</institution>
        <type>Online course</type>
        <location>—</location>
        <instructor>David Glassner</instructor>
        <date>January 17, 2019</date>
        <sortDate>2019-01-17</sortDate>
        <description>Introductory course on Java programming language. Covers how to set up Java and IntelliJ. Covers basics: variables, values, and expressions; object data types; building, comparing, parsing strings; debugging and excepton handling; loops; passing arguments by reference or value; simple and complex arryas; custom classes; inheritance and polymorphism; Java libraries; Javadoc; JAR files</description>
        <category>Java</category>
        <category>Programming</category>
    </item>
    <item>
        <title>Git and GitHub for Writers</title>
        <subject>Git, GitHub</subject>
        <institution>Udemy</institution>
        <type>Online course</type>
        <location>—</location>
        <instructor>Peter Gruenbaum</instructor>
        <date>December 27, 2018</date>
        <sortDate>2018-12-27</sortDate>
        <description>Introduction to Git and GitHub taught for writers. Covers adding, renaming, deleting, cloning repositories. Also discussed tags, pulls, branches, stashing changes, merging branches, rebasing, gitignore files, and dealing with problems in Git. Touched on documentation in GitHub and other tools like GitBook, Jekyll, or AsciiDoctor.</description>
        <category>Technical writing</category>
        <category>Git</category>
        <category>GitHub</category>
        <category>Command line</category>
    </item>
    <item>
